# Generated by Django 3.2.5 on 2025-05-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.IntegerField(),
        ),
    ]
