# Generated by Django 3.2.5 on 2025-05-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='Description', max_length=1024),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='Projet', max_length=128),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.CharField(default='Commentaire', max_length=1024),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.CharField(default='Description', max_length=1024),
        ),
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(default='Issue', max_length=128),
        ),
    ]
