# Generated by Django 5.2.1 on 2025-05-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportAPI', '0002_alter_user_can_be_contacted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
