# Generated by Django 3.2.5 on 2025-05-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supportAPI', '0002_auto_20250515_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='can_be_contcted',
            new_name='can_be_contacted',
        ),
    ]
