# Generated by Django 3.2.5 on 2025-05-15 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supportAPI', '0003_rename_can_be_contcted_user_can_be_contacted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='supportAPI.user'),
        ),
    ]
