# Generated by Django 5.2.1 on 2025-05-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supportAPI', '0003_alter_user_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
