# Generated by Django 3.2.5 on 2025-05-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supportAPI', '0006_auto_20250515_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Issue',
            new_name='issue',
        ),
    ]
