# Generated by Django 3.2.5 on 2025-05-16 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supportAPI', '0007_rename_issue_comment_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='supportAPI.user'),
        ),
    ]
